### ISSUE TITLE
Unable to update config of kubernetes service

### ISSUE THREAD

**Issue by engapa** [mesosphere/dcos-kubernetes-quickstart#81]
When someone wants to change some parameters of configuration, for example change the number of kubernetes cpus from default values:

```yaml
{
  "kubernetes": {
    "high_availability": true,
    "node_count": 3,
    "public_node_count": 1
  }
}
```
to:
```yaml
{
 "kubernetes": {
   "high_availability": true,
   "node_count": 3,
   "public_node_count": 1,
   "reserved_resources": {
     "kube_cpus": 5
   }
 }
}
```
WE never get a ready kubernetes service. And by using the dcos update command then plans never end successfully.

All tests were launched on GCP. With the following desired_cluster_profile.gcp contents:

```text
num_of_masters = "1"
num_of_private_agents = "3"
num_of_public_agents = "1"

gcp_bootstrap_instance_type = "n1-standard-1"
gcp_master_instance_type = "n1-standard-8"
gcp_agent_instance_type = "n1-standard-8"
gcp_public_agent_instance_type = "n1-standard-8"
```
